push_api="https://luffa.putdev.com/post/sendMessage"
[store]
path = "~/.local/share/boot/store"
[p2p]
libp2p = {listening_multiaddrs = ["/ip4/0.0.0.0/udp/8899/quic-v1"],bootstrap_peers=[]}
key_store_path = "~/share/boot"




