[package]
name = "luffa-process"
version.workspace = true
edition.workspace = true


[dependencies]
anyhow.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["signal", "process"] }