[p2p]
libp2p = { listening_multiaddrs = ["/ip4/0.0.0.0/udp/0/quic-v1"],bootstrap_peers=["/ip4/192.168.2.124/udp/8899/quic-v1/p2p/12D3KooWRxHCJhGZMpUvfVHGx2iK6NMtPSCtC3AVrvQ7B8rAnuYL"]}
key_store_path = "~/.local/share/client1"