[p2p]
libp2p = { listening_multiaddrs = ["/ip4/0.0.0.0/udp/0/quic-v1"],bootstrap_peers=["/ip4/206.238.220.40/udp/8899/quic-v1/p2p/12D3KooWLm17MWN8mq1XkiUmt74t12pqk2B3fMAYTww1Fq9Z8j7N"]}
key_store_path = "~/.local/share/client1"