[p2p]
libp2p = { listening_multiaddrs = ["/ip4/0.0.0.0/udp/0/quic-v1"],bootstrap_peers=["/ip4/206.238.220.40/udp/8899/quic-v1/p2p/12D3KooWDyjzAiWnZ11H8SGkL11WmB4UJxcmFQirMuyZPPqnyZAD"]}
key_store_path = "/home/snqu/.local/share/client1"
rpc_client = {p2p_addr = "irpc://127.0.0.1:30001"}

[rpc_client]
p2p_addr = "irpc://127.0.0.1:30001"